name: pigeon_map
version: 0.2.004
author: tatumizer <tatumizer@gmail.com>
description: efficient Map and Map-backed struct, with fast serializers
homepage: https://github.com/tatumizer/pigeon_map
environment:
  sdk: '>=0.5.0'
dev_dependencies:
  unittest: <=1.0.0
